language: python
python:
  - "2.7"

env:
  - DJANGO=Django==1.8

install:
  - sudo apt-get update
  - sudo apt-get install libxml2
  - pip install $DJANGO
  - pip install -r requirements.txt

script: ./build.sh

services:
  - postgresql

before_script:
  - psql -c 'create database bijgeschaafd_test;' -U postgres
