language: python
python:
  - "2.7"

env:
  - DJANGO=Django==1.8

install:
  - sudo apt-get update
  - sudo apt-get install libxml2
  - pip install $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors

script: ./build.sh
